apiVersion: apps/v1
kind: Deployment
metadata:
  # reger
  labels:
    app: javaapp
  name: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - image: quay.io/satishchennu1/javaapp:latest
          imagePullPolicy: Always
          name: javaapp
          ports:
            - containerPort: 8080
